// <auto-generated />
using System;
using HotelHenry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelHenry.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20200805045206_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelHenry.Models.Habitacion", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHabitacion");

                    b.ToTable("Habitacions");
                });

            modelBuilder.Entity("HotelHenry.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nombre")
                        .HasColumnType("int");

                    b.HasKey("IdPais");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("HotelHenry.Models.Reservacion", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantHabitaciones")
                        .HasColumnType("int");

                    b.Property<string>("Correo1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaisIdPais")
                        .HasColumnType("int");

                    b.Property<int?>("RolIdRol")
                        .HasColumnType("int");

                    b.Property<int?>("TipoHabitacionIdHabitacion")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("Correo1");

                    b.HasIndex("PaisIdPais");

                    b.HasIndex("RolIdRol");

                    b.HasIndex("TipoHabitacionIdHabitacion");

                    b.ToTable("Reservacions");
                });

            modelBuilder.Entity("HotelHenry.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("HotelHenry.Models.Usuario", b =>
                {
                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaisIdPais")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolIdRol")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Correo");

                    b.HasIndex("PaisIdPais");

                    b.HasIndex("RolIdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HotelHenry.Models.Reservacion", b =>
                {
                    b.HasOne("HotelHenry.Models.Usuario", "Correo")
                        .WithMany("Reservacion")
                        .HasForeignKey("Correo1");

                    b.HasOne("HotelHenry.Models.Pais", null)
                        .WithMany("Reservacion")
                        .HasForeignKey("PaisIdPais");

                    b.HasOne("HotelHenry.Models.Rol", null)
                        .WithMany("Reservacion")
                        .HasForeignKey("RolIdRol");

                    b.HasOne("HotelHenry.Models.Habitacion", "TipoHabitacion")
                        .WithMany("Reservacion")
                        .HasForeignKey("TipoHabitacionIdHabitacion");
                });

            modelBuilder.Entity("HotelHenry.Models.Usuario", b =>
                {
                    b.HasOne("HotelHenry.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisIdPais");

                    b.HasOne("HotelHenry.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolIdRol");
                });
#pragma warning restore 612, 618
        }
    }
}
